### ISSUE TITLE
CONECTAR MONDE COM BITRIX VIA API

### ISSUE THREAD

**Issue by EduardoLiber** [monde-sistemas/monde-api#33]
Olá. Preciso de um help.

Estou precisando conectar cadastro de pessoas do monde com o bitrix24 via API. Alguém consegue me orientar quais o passo a passo?

**Comment by RoneiBienert** [comment]
As informações para conexão com nossa API estão listadas no [Ajuda Monde](https://monde.movidesk.com/kb/article/222677/integracao-api?ticketId=&q=api) e também no [Readme](https://github.com/monde-sistemas/monde-api#readme) deste projeto.

Porem referente ao bitrix24 você pode entrar em contato diretamente com suporte deles solicitando ajuda para configuração de Integração de sistema de terceiros aonde é possível fazer a importação ou integração dos clientes.
